// Type definitions for Flare Worker
// Note: Env is generated by `wrangler types` in worker-configuration.d.ts

export interface ExecuteRequest {
  function_id: string;
  code: string;
  function_name: string;
  args: string; // Hex-encoded cloudpickle
  kwargs: string; // Hex-encoded cloudpickle
  timeout?: number; // Execution timeout in seconds (default: 300)
  env?: Record<string, string>; // Environment variables to inject into sandbox
}

export interface ExecuteResponse {
  success: boolean;
  result?: string; // Hex-encoded cloudpickle result
  stdout?: string;
  stderr?: string;
  error?: string;
  execution_time_ms?: number;
  sandbox_id?: string;
  started_at?: string; // ISO timestamp
  completed_at?: string; // ISO timestamp
}

export interface ExecuteBatchResponse {
  results: ExecuteResponse[];
  total_execution_time_ms?: number;
  batch_count?: number;
  max_containers?: number;
}
